"""The runtime bundle's file templates, as plain Python string constants.

Templates live as ``string.Template`` constants rather than packaged data
files so the package stays wheel-simple (no ``package_data`` plumbing, no
resource loading). Two delimiter regimes keep escaping sane:

- :data:`COMPOSE_TEMPLATE` uses ``%``-placeholders (:class:`ComposeTemplate`)
  because the compose file is full of ``${VAR}`` interpolations that Docker
  Compose itself resolves from ``.env``, plus ``$$``-escaped shell variables
  in the embedded bash script -- a ``$`` delimiter would force ``$$$$``
  quadruple escaping.
- The DAG templates (:data:`MASTER_DAG_TEMPLATE` and the two sub-DAG
  templates) are standard ``$``-delimiter templates; the generated Python
  source contains no ``$``.

Every Airflow fact encoded here (service set, exact env var names, the
health endpoint, JWT auth, external-python constraints) is cited in
references/airflow3-notes.md.
"""

from string import Template

# The DAG-bundle list every rendering shares (references/airflow3-notes.md,
# "DAG bundles"): Compose injects it into the containers' environment, and
# `hflow deploy`'s DEPLOY.md quotes it verbatim for self-managed Airflow.
# One owner for the JSON so the two paths can never drift.
DAG_BUNDLE_CONFIG_LIST_JSON = (
    '[{"name": "dags-folder", '
    '"classpath": "airflow.dag_processing.bundles.local.LocalDagBundle", '
    '"kwargs": {"path": "/opt/airflow/dags"}}]'
)


# The ONLY package the user venv needs besides hflow and the user's own
# dependencies: ExternalPythonOperator's per-task bootstrap probe is exactly
# `import pendulum` when expect_airflow=False, and lazy_object_proxy never
# crosses into the venv because proxies resolve host-side before pickling.
# Pinned to apache/airflow:3.3.1's own constraint so a future pendulum major
# cannot break context unpickling. One owner, because both renderers install
# it and a drift between them is a task that fails its probe on one path only.
EXTERNAL_PYTHON_BOOTSTRAP_REQUIREMENT = "pendulum==3.2.0"


class ComposeTemplate(Template):
    """``string.Template`` with ``%name`` / ``%{name}`` placeholders.

    Chosen so the compose file's own ``${VAR}`` interpolation syntax and the
    ``$$``-escaped bash variables pass through untouched; the template text
    must therefore contain no literal ``%`` outside placeholders.
    """

    delimiter = "%"


# The official Airflow 3.3.1 reference compose reduced to LocalExecutor:
# postgres + airflow-init + user-venv-init +
# apiserver/scheduler/dag-processor/triggerer, no redis, no celery worker,
# no flower. Substitutions: %{data_volume_line}
# (local mode: the host data root mounted at /opt/airflow/data; bucket mode:
# the bundle-local ./xcom directory instead -- episodes never touch the host
# filesystem), %{xcom_objectstorage_path} (under whichever of those mounts
# exists), %{dag_bundle_config_list} (the shared
# :data:`DAG_BUNDLE_CONFIG_LIST_JSON`), %{hflow_install_target} (the
# source path, plus the [bucket] extra for bucket data roots),
# %{bucket_credentials_env}/%{bucket_credentials_mount} (provider credential
# passthrough for bucket data roots; empty in local mode), and the two
# optional hflow-source mount suffixes (empty when unset).
COMPOSE_TEMPLATE = ComposeTemplate(
    """\
# Generated by hflow render_bundle -- re-rendering overwrites this file
# (only .env survives re-renders). The Airflow 3.3.1 reference compose
# reduced to LocalExecutor: broker and distributed-worker services removed.
# Facts cited in references/airflow3-notes.md.

# A unique project name per bundle: without it Compose defaults to the bundle
# directory's basename ("runtime" for every default bundle), so two projects
# on one machine would silently adopt and destroy each other's stacks and
# share named volumes.
name: %{project_name}

x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE}
  user: "${AIRFLOW_UID}:0"
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    # ${POSTGRES_PASSWORD:-airflow}: generated per bundle into .env; the
    # default keeps bundles rendered by older versions (whose preserved .env
    # has no POSTGRES_PASSWORD) working against their existing DB volume.
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD:-airflow}@postgres/airflow
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__API_AUTH__JWT_SECRET: ${JWT_SECRET}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DAG_PROCESSOR__DAG_BUNDLE_CONFIG_LIST: '%{dag_bundle_config_list}'
    AIRFLOW__CORE__XCOM_BACKEND: airflow.providers.common.io.xcom.backend.XComObjectStorageBackend
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_PATH: %{xcom_objectstorage_path}
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_THRESHOLD: '4096'
    # hflow's pinned ffmpeg (a measuring instrument, downloaded once and
    # sha256-verified) caches under XDG_CACHE_HOME; pointing it into the
    # user-venv volume makes the download survive container restarts instead
    # of repeating into an ephemeral container home. Bucket data roots also
    # put their spool mirrors under this cache, so downloads persist too.
    XDG_CACHE_HOME: /opt/venvs/cache%{bucket_credentials_env}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs%{data_volume_line}
    # Mount target must match hflow.stage_execution.USER_DIRECTORY_DEFAULT.
    - ./user:/opt/user:ro
    - user-venv:/opt/venvs%{airflow_hflow_source_mount}%{bucket_credentials_mount}
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully
    user-venv-init:
      condition: service_completed_successfully

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-init:
    <<: *airflow-common
    # The official image entrypoint migrates the DB and creates the admin
    # user when the _AIRFLOW_* variables below are set; `version` is the
    # no-op command it runs afterwards (the reference compose's init idiom).
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  user-venv-init:
    # Build the user's venv inside the shared named volume. This runs as root
    # because Docker creates a fresh named volume root-owned (the
    # airflow uid cannot write it); ownership is handed to ${AIRFLOW_UID}:0
    # before exiting so the task processes can use the venv and cache. The
    # content-hash marker is a create-if-absent checkpoint: unchanged
    # requirements + hflow source skip the rebuild entirely.
    image: ${AIRFLOW_IMAGE}
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -euo pipefail
        mkdir -p /opt/venvs/cache
        marker_file=/opt/venvs/user/.hflow-content-hash
        # uv, which apache/airflow ships on PATH, resolves and installs an
        # order of magnitude faster than pip and reads the user's uv.lock
        # directly -- so a locked project gets the exact versions it locked.
        export UV_PROJECT_ENVIRONMENT=/opt/venvs/user
        # The image's default cache is under /tmp: ephemeral, and on a
        # different filesystem from the volume, so every rebuild would
        # re-download everything.
        export UV_CACHE_DIR=/opt/venvs/uv-cache
        # Never fetch a managed interpreter. The venv must be the IMAGE's
        # Python or the external-python pickle boundary breaks between
        # Airflow's process and the task's.
        export UV_PYTHON_DOWNLOADS=never
        # The image exports VIRTUAL_ENV=/home/airflow/.local -- Airflow's OWN
        # environment. Left set, uv would treat it as the target.
        unset VIRTUAL_ENV
        venv_python=/opt/venvs/user/bin/python
        # pendulum silences ExternalPythonOperator's noisy per-task bootstrap
        # probe -- at providers-standard 1.17.0 the venv probe is exactly
        # `import pendulum`, and lazy_object_proxy never crosses into the venv
        # (proxies resolve host-side before pickling), so it is NOT installed.
        # The pin matches apache/airflow:3.3.1's constraint so a future
        # pendulum major can never break context unpickling. Joins the hash
        # input so previously built venvs rebuild exactly once.
        bootstrap_packages="%{external_python_bootstrap_requirement}"
        hflow_install_target='%{hflow_install_target}'
        hflow_expected_version='%{hflow_expected_version}'
        desired_hash="$$({ echo "bootstrap: $$bootstrap_packages"; echo "install: $$hflow_install_target"; cat /opt/user/pyproject.toml 2>/dev/null || true; cat /opt/user/uv.lock 2>/dev/null || true; cat /opt/user/requirements.txt 2>/dev/null || true; cat /opt/hflow-src/pyproject.toml 2>/dev/null || true; } | sha256sum | cut -d ' ' -f 1)"
        if [ -f "$$marker_file" ] && [ "$$(cat "$$marker_file")" = "$$desired_hash" ]; then
          chown "${AIRFLOW_UID}:0" /opt/venvs /opt/venvs/cache
          echo "user venv matches content hash $$desired_hash -- skipping rebuild"
          exit 0
        fi
        echo "building user venv for content hash $$desired_hash"
        rm -rf /opt/venvs/user
        uv venv --python "$$(command -v python)" /opt/venvs/user
        # A locked project first, then a bare pyproject, then requirements.txt
        # -- and requirements.txt applies on top either way, so the legacy
        # escape hatch keeps working beside a project.
        if [ -f /opt/user/uv.lock ]; then
          # --inexact: the target venv also holds pendulum and hflow, which are
          # OURS, not the user's. Without it uv prunes them and every stage
          # task fails its bootstrap probe.
          # --no-install-project: /opt/user is mounted read-only, and a build
          # backend writing metadata into the source tree would fail there.
          uv sync --project /opt/user --frozen --inexact --no-install-project
        elif [ -f /opt/user/pyproject.toml ]; then
          uv pip install --python "$$venv_python" -r /opt/user/pyproject.toml
        fi
        if [ -f /opt/user/requirements.txt ]; then
          uv pip install --python "$$venv_python" -r /opt/user/requirements.txt
        fi
        uv pip install --python "$$venv_python" $$bootstrap_packages "$$hflow_install_target"
        uv pip check --python "$$venv_python" || echo "warning: user venv has conflicting dependencies (see above)" >&2
        # The rendered DAGs call this library; a user lockfile pinning another
        # hflow would run generated code against a version it was not rendered
        # for. Before this, the bundle's own install target made skew
        # impossible; a project's lockfile can now win the resolution, so the
        # guarantee has to be checked instead of assumed.
        installed_hflow_version="$$("$$venv_python" -c 'import hflow; print(hflow.__version__)')"
        if [ "$$installed_hflow_version" != "$$hflow_expected_version" ]; then
          echo "user venv has hflow $$installed_hflow_version but these DAGs were rendered by $$hflow_expected_version; pin hflow==$$hflow_expected_version in your project" >&2
          exit 1
        fi
        # Pre-warm the pinned ffmpeg into the volume-backed cache so the
        # download happens here, under the user's eyes at provision time,
        # instead of stalling the first task. Best-effort (|| true): air-gapped
        # provisioning must still succeed -- the task-time fallback remains.
        XDG_CACHE_HOME=/opt/venvs/cache /opt/venvs/user/bin/python -c 'from hflow.ffmpeg import ffmpeg_path; ffmpeg_path()' || true
        echo "$$desired_hash" > "$$marker_file"
        chown -R "${AIRFLOW_UID}:0" /opt/venvs
    volumes:
      - user-venv:/opt/venvs
      # Mount target must match hflow.stage_execution.USER_DIRECTORY_DEFAULT.
      - ./user:/opt/user:ro%{venv_init_hflow_source_mount}

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      # ${API_BIND_HOST:-127.0.0.1}: loopback-only by default (a workspace
      # exposes nothing); a hosted data plane fronted by its own gateway can
      # widen the bind through .env without editing this file.
      - "${API_BIND_HOST:-127.0.0.1}:${API_PORT}:8080"
    healthcheck:
      # /api/v2/monitor/health always answers HTTP 200 (the body carries the
      # per-component statuses); this checks the api-server answers at all,
      # exactly like the reference compose's own healthcheck.
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always

volumes:
  postgres-db-volume:
  user-venv:
"""
)


# The master ingest DAG (the master half of the ingest stage graph), shared
# by the Compose runtime (render_bundle) and `hflow deploy`
# (render_deploy_bundle).
# Substitutions: $dag_id, the four $*_dag_id sub-DAG ids, and
# $run_profiles_literal -- a dict literal baked from hflow.steps.
# RUN_PROFILES at render time (steps.py stays the one owner of the profile
# vocabulary; the baked copy is generated code). The master runs ENTIRELY in
# Airflow's own environment: no external_python, no hflow import --
# TriggerDagRunOperator ships in apache-airflow-providers-standard, which the
# official image includes, and its deferrable wait needs the triggerer
# service, which every rendered runtime runs.
MASTER_DAG_TEMPLATE = Template(
    '''\
"""Master ingest DAG "$dag_id" -- generated by hflow; re-render instead of editing.

The master half of the ingest stage graph: resolve the run profile to its
enabled stage set, then trigger only those sub-DAGs, chained sequentially
(sync >> meta >> labels >> media). Runs entirely in Airflow's own environment
-- no user venv, no hflow import.

Trigger conf: {"uris": [...], "profile": "full", "mode": "batch"|"online",
"batch_count": optional int, "all_stages": optional bool}.
"uris"/"mode"/"batch_count"/"all_stages" pass through to
every triggered sub-DAG; mode "online" is the latency-first lane (one run per
episode as it lands): each sub-DAG processes the conf's uris as one immediate
batch, no bin-packing, no stagger.

How the stage graph's profile toggles map onto tasks: the profile arrives in
the run conf, so which stages run cannot be a parse-time conditional. Instead every
stage's trigger always exists behind its own enabled_<stage> gate task, and a
gate raises AirflowSkipException when the resolved profile disables its stage
-- the skip cascades to exactly that stage's trigger (default all_success
rule), while the next gate's trigger_rule="none_failed" lets it run after
skipped (but never failed) predecessors. So the enabled sub-DAGs execute
strictly in sequence, a disabled stage shows as two skipped tasks in the UI,
and a failed sub-DAG still stops the chain. Deliberately NOT a @task.branch:
skip_all_except treats everything downstream of a followed branch as also
followed, and with the triggers chained sequentially that would silently
re-enable every stage after the first enabled one (a "labels"-only profile
would run media too).
"""

from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.sdk import dag, task

# Baked from hflow.steps.RUN_PROFILES and hflow.steps.IngestMode at render
# time -- re-render after changing either; never edit these literals by hand.
RUN_PROFILE_STAGES = $run_profiles_literal
VALID_INGEST_MODES = $ingest_modes_literal

# Declaration order is the stage graph's execution order.
STAGE_SUB_DAG_IDS = {
    "sync": "$sync_dag_id",
    "meta": "$meta_dag_id",
    "labels": "$labels_dag_id",
    "media": "$media_dag_id",
}

# Rendered on the DAG's page in the Airflow UI (the profile table is baked
# from hflow.steps.RUN_PROFILES at render time, like the literal above).
DOC_MD = """\
## Master ingest -- resolves the run profile, triggers only the sub-DAGs it needs

The master half of the ingest stage graph. Enabled stages run strictly in
order (sync >> meta >> labels >> media); a stage disabled by the profile shows as
two **skipped** tasks, and a teal **deferred** trigger task is intentionally
waiting on its sub-DAG run to finish.

| run profile | stages enabled |
|---|---|
$profile_table_rows

**Trigger conf** -- `uris`: episode files relative to the data root;
`profile`: a row above (default `full`); `mode`: `batch` bin-packs uris into
staggered near-equal-byte shards, `online` is the latency-first lane (one
immediate run, no batching, no stagger); `batch_count`: optional override;
`all_stages`: run every stage over everything it is handed instead of only
what the catalog does not already record as current.

Each sub-DAG (`$sync_dag_id`, `$meta_dag_id`, `$labels_dag_id`,
`$media_dag_id`) is also directly triggerable with the same conf for
per-stage reruns -- e.g. a re-label pass over already-canonical episodes.
"""


@dag(
    dag_id="$dag_id",
    dag_display_name="$master_display_name",
    description="Resolves the run profile and triggers only the enabled stage sub-DAGs.",
    doc_md=DOC_MD,
    tags=["$pipeline_tag", "master"],
    schedule=None,
    render_template_as_native_obj=True,
    params={
        "uris": [],
        "profile": "full",
        "mode": "batch",
        "batch_count": None,
        "all_stages": False,
    },
)
def master_ingest():
    @task
    def resolve_profile(profile, mode):
        """Validate the conf against the baked vocabulary; return the enabled stages."""
        if profile not in RUN_PROFILE_STAGES:
            raise ValueError(
                f"unknown run profile {profile!r}; valid profiles: "
                f"{sorted(RUN_PROFILE_STAGES)}"
            )
        if mode not in VALID_INGEST_MODES:
            raise ValueError(
                f"unknown mode {mode!r}; valid modes: {', '.join(VALID_INGEST_MODES)}"
            )
        return list(RUN_PROFILE_STAGES[profile])

    @task(trigger_rule="none_failed")
    def stage_gate(stage_name, enabled_stage_names):
        """Skip this stage's trigger when the profile disables it (a stage toggle)."""
        from airflow.exceptions import AirflowSkipException

        if stage_name not in enabled_stage_names:
            raise AirflowSkipException(
                f"stage {stage_name!r} disabled by the run profile "
                f"(enabled: {enabled_stage_names})"
            )

    enabled_stage_names = resolve_profile(
        profile="{{ params.profile }}", mode="{{ params.mode }}"
    )

    previous_trigger = None
    for stage_name, sub_dag_id in STAGE_SUB_DAG_IDS.items():
        gate = stage_gate.override(task_id=f"enabled_{stage_name}")(
            stage_name, enabled_stage_names
        )
        trigger = TriggerDagRunOperator(
            task_id=f"trigger_{stage_name}",
            # A teal "deferred" state reads as stalled to demo audiences;
            # the display name and doc say the wait is intentional.
            task_display_name=f"trigger {stage_name} · waits (deferred)",
            doc_md=(
                f"Triggers `{sub_dag_id}` and waits (deferred, checked every "
                "5s) for that run to finish before the next stage's gate."
            ),
            trigger_dag_id=sub_dag_id,
            conf={
                "uris": "{{ params.uris }}",
                "mode": "{{ params.mode }}",
                "batch_count": "{{ params.batch_count }}",
                "all_stages": "{{ params.all_stages }}",
            },
            wait_for_completion=True,
            deferrable=True,
            # Measured (2026-08-18): the deferral wait wastes ~poke_interval/2
            # per hop after a sub-DAG finishes; at local run volumes a 2s poll
            # costs the triggerer nothing and saves ~1.5s per stage hop.
            poke_interval=2,
        )
        gate >> trigger
        if previous_trigger is not None:
            previous_trigger >> gate
        previous_trigger = trigger


master_ingest()
'''
)


# The sub-DAG templates (the stage graph's four toggleable sub-DAGs), shared
# by the Compose runtime and `hflow deploy`. Substitutions: $dag_id,
# $master_dag_id, $stage_title, $stage_name, $gate_name, $pipeline_filename,
# $app_variable, plus the two facts the deployments disagree on -- $data_root
# (where episode URIs resolve inside the task processes) and $venv_python
# (the user venv's interpreter). Every task runs via @task.external_python
# against the user venv, so ALL imports live inside the function bodies (the
# operator extracts each body to a temp file; module globals do not survive)
# and everything passed between tasks is plain JSON-able data. The two
# variants differ only in the gate: checks decide quarantine, so the
# quarantine budget lives ONLY in the meta sub-DAG; every other stage keeps
# the error-budget half.
_SUB_DAG_HEADER = '''\
"""$stage_title sub-DAG "$dag_id" -- generated by hflow; re-render instead of editing.

One of the ingest stage graph's four toggleable sub-DAGs, normally triggered
by the master DAG "$master_dag_id" (direct triggering with the same conf also
works).
plan -> process_batch (dynamically mapped) -> $gate_name, all via
@task.external_python against the user venv at $venv_python_doc (user dependencies
never meet Airflow's pins). Imports live inside the function bodies because
the operator extracts each body to a temp file; only JSON-able data crosses
task borders. Trigger conf: {"uris": [...], "mode": "batch"|"online",
"batch_count": optional int, "all_stages": optional bool}.
"""

from airflow.sdk import dag, task

# Rendered on the DAG's page in the Airflow UI.
DOC_MD = """\
## $stage_title -- stage sub-DAG

$stage_description

Normally triggered by the master DAG `$master_dag_id` (its run profile
decides which stages run); triggering it directly with the same conf
also works, for per-stage reruns. Tasks execute in the isolated user venv --
user dependencies never meet Airflow's pins.

**Trigger conf** -- `uris`: episode files relative to the data root;
`mode`: `batch` (bin-packed, staggered shards) or `online` (one immediate
latency-first run); `batch_count`: optional override; `all_stages`: run every
uri handed over instead of only the ones this stage still owes work on.
"""


@dag(
    dag_id="$dag_id",
    dag_display_name="$sub_display_name",
    description="$stage_description",
    doc_md=DOC_MD,
    tags=["$pipeline_tag", "stage:$stage_name"],
    schedule=None,
    render_template_as_native_obj=True,
    params={"uris": [], "mode": "batch", "batch_count": None, "all_stages": False},
)
def ingest_stage():
    @task.external_python(python=$venv_python, expect_airflow=False, skip_on_exit_code=99$task_queue_argument)
    def plan(uris, mode, batch_count, all_stages):
        """Narrow uris to what this stage still owes, then bin-pack them.

        The lane semantics live in hflow.stage_execution (one owner for every
        execution backend); this task only feeds it the trigger conf. Any
        narrowing happens first, so the bin-packer only ever sees work that
        is going to run.

        all_stages is the conf escape hatch: true runs every uri handed over,
        whatever the catalog already records. It is the scheduled counterpart
        of `hflow ingest --all-stages`, and exists for the one thing the
        catalog cannot see -- an artifact deleted out from under a step whose
        rows still say it ran.
        """
        from hflow.stage_execution import parse_conf_flag, plan_stage_batches

        if not uris:
            return []
        # The conf vocabulary is parsed at the library boundary, like mode --
        # this task only feeds it what Airflow rendered.
        all_stages = parse_conf_flag(all_stages)
$stage_plan_filter        return plan_stage_batches(
            [str(uri) for uri in uris],
            mode=mode,
            batch_count=batch_count,
            data_root=$data_root,
        )

    @task.external_python(python=$venv_python, expect_airflow=False$task_queue_argument)
    def process_batch(batch, orchestrator_run_id):
        """Sleep the stagger delay, then run this sub-DAG's stage on every episode.

        The pipeline-loading contract and the per-episode accounting loop live
        in hflow.stage_execution; this task binds them to the rendered
        data root and pipeline file.

        orchestrator_run_id arrives as a rendered template argument, not from the
        Airflow context: expect_airflow=False means Airflow is not importable
        in the user venv this runs in, so the run id has to be handed over
        from the DAG side. It is recorded on every episode the batch appends.
        """
        import os
        import time

        from hflow.app import DATA_ROOT_ENVIRONMENT_VARIABLE
        from hflow.stage_execution import (
            load_pipeline_application,
            process_stage_batch,
            require_application_data_root,
            resolve_user_pipeline_path,
        )

        time.sleep(float(batch["start_delay_s"]))

        expected_data_root = $data_root
        # Environment-portable pipelines (App constructed without an explicit
        # data_root) resolve their root from this variable; a pipeline that
        # hardcodes a different literal is refused by the guard below.
        os.environ[DATA_ROOT_ENVIRONMENT_VARIABLE] = expected_data_root
        pipeline_path = resolve_user_pipeline_path($pipeline_filename)
        app = load_pipeline_application(pipeline_path, "$app_variable")
        require_application_data_root(app, expected_data_root)
        return process_stage_batch(app, batch["items"], "$stage_name", orchestrator_run_id)
'''

_SUB_DAG_QUARANTINE_GATE = '''\

    @task.external_python(python=$venv_python, expect_airflow=False$task_queue_argument)
    def quarantine_budget_gate(batch_counts):
        """Fail the run loudly on mass failure of either kind.

        Checks decide quarantine, so the quarantine budget lives ONLY in this
        meta sub-DAG. The budget math is library-owned
        (hflow.stage_execution), shared by every execution backend.
        """
        from hflow.stage_execution import summarize_quarantine_budget

        return summarize_quarantine_budget(batch_counts)
'''

_SUB_DAG_ERROR_GATE = '''\

    @task.external_python(python=$venv_python, expect_airflow=False$task_queue_argument)
    def error_budget_gate(batch_counts):
        """Fail loudly when processing errors exceed the run budget.

        Quarantine budgets live only in the meta sub-DAG (checks decide
        quarantine). The budget math is library-owned
        (hflow.stage_execution), shared by every execution backend.
        """
        from hflow.stage_execution import summarize_error_budget

        return summarize_error_budget(batch_counts)
'''

_SUB_DAG_FOOTER = """\

    batches = plan(
        uris="{{ params.uris }}",
        mode="{{ params.mode }}",
        batch_count="{{ params.batch_count }}",
        all_stages="{{ params.all_stages }}",
    )
    # partial() binds the run id once for every mapped instance: it is the
    # same value for the whole fan-out, and only expand()'s argument varies.
    # "{{ run_id }}" is THIS sub-DAG's run id, which is what the runs API
    # reports for this stage, so a catalog row joins straight to the run the
    # UI is drawing. Rendering happens DAG-side, before the external-python
    # callable is invoked, which is the only way in (expect_airflow=False).
    batch_counts = process_batch.partial(orchestrator_run_id="{{ run_id }}").expand(batch=batches)
    # The mapped task's aggregated XCom is a lazy proxy that cannot cross the
    # external-python pickle boundary (it references the in-DAG callable), so
    # the gate pulls it via a template: `| list` materializes plain dicts
    # during native-object rendering. task_ids MUST be a list -- a plain
    # string makes xcom_pull flatten a single-batch run to the bare counts
    # dict. The >> keeps the dependency explicit.
    gate = $gate_name(
        batch_counts="{{ ti.xcom_pull(task_ids=['process_batch']) | list }}"
    )
    batch_counts >> gate


ingest_stage()
"""

SUB_DAG_QUARANTINE_GATE_TEMPLATE = Template(
    _SUB_DAG_HEADER + _SUB_DAG_QUARANTINE_GATE + _SUB_DAG_FOOTER
)
SUB_DAG_ERROR_GATE_TEMPLATE = Template(_SUB_DAG_HEADER + _SUB_DAG_ERROR_GATE + _SUB_DAG_FOOTER)


# Injected into the media sub-DAG's plan (empty for other stages, and for
# BUCKET data roots -- reading a remote episode's channel list would download
# the whole file, which costs more than the skipped cycle saves): media
# derives per-camera artifacts, so camera-less episodes would pay a full
# plan -> map -> gate cycle (~10s measured 2026-08-18) to record nothing.
# When nothing in the run has cameras the plan exits 99, which
# skip_on_exit_code turns into a SKIPPED task (the UI shows the stage never
# applied, not a hollow success); downstream tasks skip with it.
MEDIA_PLAN_FILTER_TEMPLATE = Template(
    """\
        from pathlib import Path

        from hflow.format import CAMERA_SCHEMA_NAMES
        from hflow.reader import open_reader

        def has_camera(uri):
            reader = open_reader(Path($data_root) / str(uri))
            try:
                return any(
                    info.schema_name in CAMERA_SCHEMA_NAMES
                    for info in reader.channels().values()
                )
            finally:
                reader.close()

        # Media applies only to camera-bearing episodes (see template note).
        uris = [uri for uri in uris if has_camera(uri)]
        if not uris:
            raise SystemExit(99)  # skip_on_exit_code: whole stage SKIPPED
"""
)


# Injected into every stage sub-DAG's plan EXCEPT sync's (sync records no
# steps and is its own cache, so it is never planned away). Asks the catalog
# which of this run's uris still owe this stage work at the steps' current
# versions, and drops the rest -- the same question `hflow ingest` asks
# in-process, in the same place relative to sync, so the two lanes cost the
# same for the same command.
#
# Placed BEFORE the media filter when a stage has both: this one is a catalog
# query, the media one opens episodes, and narrowing first means fewer files
# to open.
#
# Loading the user pipeline here is what the question costs. plan already runs
# in the user venv (@task.external_python), and these are the same three
# helpers process_batch calls, so nothing new is introduced -- but a pipeline
# that will not import now fails at plan rather than at process_batch, which
# is earlier and cheaper to read.
#
# When nothing is left the plan exits 99, which skip_on_exit_code turns into a
# SKIPPED task (the UI shows a stage that had nothing to do, not a hollow
# success); downstream tasks skip with it.
OUTSTANDING_PLAN_FILTER_TEMPLATE = Template(
    """\
        if not all_stages:
            import os

            from hflow.app import DATA_ROOT_ENVIRONMENT_VARIABLE
            from hflow.stage_execution import (
                load_pipeline_application,
                require_application_data_root,
                resolve_user_pipeline_path,
            )
            from hflow.stage_planning import outstanding_stage_uris
            from hflow.steps import Stage

            expected_data_root = $data_root
            # Same guard process_batch applies: an environment-portable
            # pipeline resolves its root from this variable, and one that
            # hardcodes a different literal is refused rather than planned
            # against the wrong catalog.
            os.environ[DATA_ROOT_ENVIRONMENT_VARIABLE] = expected_data_root
            planning_app = load_pipeline_application(
                resolve_user_pipeline_path($pipeline_filename), "$app_variable"
            )
            require_application_data_root(planning_app, expected_data_root)
            uris = outstanding_stage_uris(
                planning_app,
                [str(uri) for uri in uris],
                Stage("$stage_name"),
                data_root=expected_data_root,
            )
            if not uris:
                raise SystemExit(99)  # skip_on_exit_code: whole stage SKIPPED
"""
)
